// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Veises.SocialNet.Identity.Contracts
{
	using Microsoft.Rest;
	using Models;
	using Newtonsoft.Json;
	using System.Collections;
	using System.Collections.Generic;
	using System.Threading;
	using System.Threading.Tasks;

	/// <summary>
	/// User identity API service
	/// </summary>
	public partial interface IVeisesUserIdentityAPI10: System.IDisposable
	{
		/// <summary>
		/// The base URI of the service.
		/// </summary>
		System.Uri BaseUri { get; set; }

		/// <summary>
		/// Gets or sets json serialization settings.
		/// </summary>
		JsonSerializerSettings SerializationSettings { get; }

		/// <summary>
		/// Gets or sets json deserialization settings.
		/// </summary>
		JsonSerializerSettings DeserializationSettings { get; }


		/// <summary>
		/// Get specified user identity
		/// </summary>
		/// <remarks>
		/// Get user by a unique identifier.
		/// </remarks>
		/// <param name='id'>
		/// Identity unique identificator
		/// </param>
		/// <param name='version'>
		/// </param>
		/// <param name='customHeaders'>
		/// The headers that will be added to request.
		/// </param>
		/// <param name='cancellationToken'>
		/// The cancellation token.
		/// </param>
		Task<HttpOperationResponse<UserIdentity>> ApiVversionIdentityByIdGetWithHttpMessagesAsync(string id, string version, Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

		/// <summary>
		/// Upate user identity
		/// </summary>
		/// <remarks>
		/// Update exists user identity
		/// </remarks>
		/// <param name='id'>
		/// Identity unique identificator
		/// </param>
		/// <param name='version'>
		/// </param>
		/// <param name='updateUserIdentity'>
		/// User identity information
		/// </param>
		/// <param name='customHeaders'>
		/// The headers that will be added to request.
		/// </param>
		/// <param name='cancellationToken'>
		/// The cancellation token.
		/// </param>
		Task<HttpOperationResponse<UserIdentity>> ApiVversionIdentityByIdPutWithHttpMessagesAsync(string id, string version, UpdateUserIdentity updateUserIdentity = default(UpdateUserIdentity), Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

		/// <summary>
		/// Create new user identity
		/// </summary>
		/// <remarks>
		/// Create new user identity
		/// </remarks>
		/// <param name='version'>
		/// </param>
		/// <param name='createIdentityModel'>
		/// Create user identity information
		/// </param>
		/// <param name='customHeaders'>
		/// The headers that will be added to request.
		/// </param>
		/// <param name='cancellationToken'>
		/// The cancellation token.
		/// </param>
		Task<HttpOperationResponse<UserIdentity>> ApiVversionIdentityPostWithHttpMessagesAsync(string version, CreateUserIdentity createIdentityModel = default(CreateUserIdentity), Dictionary<string, List<string>> customHeaders = null, CancellationToken cancellationToken = default(CancellationToken));

	}
}
