// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Veises.SocialNet.Identity.Contracts
{
    using Models;
    using System.Threading;
    using System.Threading.Tasks;

    /// <summary>
    /// Extension methods for VeisesUserIdentityAPI10.
    /// </summary>
    public static partial class VeisesUserIdentityAPI10Extensions
    {
            /// <summary>
            /// Get specified user identity
            /// </summary>
            /// <remarks>
            /// Get user by a unique identifier.
            /// </remarks>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='id'>
            /// Identity unique identificator
            /// </param>
            /// <param name='version'>
            /// </param>
            public static UserIdentity ApiVversionIdentityByIdGet(this IVeisesUserIdentityAPI10 operations, string id, string version)
            {
                return operations.ApiVversionIdentityByIdGetAsync(id, version).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Get specified user identity
            /// </summary>
            /// <remarks>
            /// Get user by a unique identifier.
            /// </remarks>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='id'>
            /// Identity unique identificator
            /// </param>
            /// <param name='version'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<UserIdentity> ApiVversionIdentityByIdGetAsync(this IVeisesUserIdentityAPI10 operations, string id, string version, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.ApiVversionIdentityByIdGetWithHttpMessagesAsync(id, version, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <summary>
            /// Upate user identity
            /// </summary>
            /// <remarks>
            /// Update exists user identity
            /// </remarks>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='id'>
            /// Identity unique identificator
            /// </param>
            /// <param name='version'>
            /// </param>
            /// <param name='updateUserIdentity'>
            /// User identity information
            /// </param>
            public static UserIdentity ApiVversionIdentityByIdPut(this IVeisesUserIdentityAPI10 operations, string id, string version, UpdateUserIdentity updateUserIdentity = default(UpdateUserIdentity))
            {
                return operations.ApiVversionIdentityByIdPutAsync(id, version, updateUserIdentity).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Upate user identity
            /// </summary>
            /// <remarks>
            /// Update exists user identity
            /// </remarks>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='id'>
            /// Identity unique identificator
            /// </param>
            /// <param name='version'>
            /// </param>
            /// <param name='updateUserIdentity'>
            /// User identity information
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<UserIdentity> ApiVversionIdentityByIdPutAsync(this IVeisesUserIdentityAPI10 operations, string id, string version, UpdateUserIdentity updateUserIdentity = default(UpdateUserIdentity), CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.ApiVversionIdentityByIdPutWithHttpMessagesAsync(id, version, updateUserIdentity, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <summary>
            /// Create new user identity
            /// </summary>
            /// <remarks>
            /// Create new user identity
            /// </remarks>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='version'>
            /// </param>
            /// <param name='createIdentityModel'>
            /// Create user identity information
            /// </param>
            public static UserIdentity ApiVversionIdentityPost(this IVeisesUserIdentityAPI10 operations, string version, CreateUserIdentity createIdentityModel = default(CreateUserIdentity))
            {
                return operations.ApiVversionIdentityPostAsync(version, createIdentityModel).GetAwaiter().GetResult();
            }

            /// <summary>
            /// Create new user identity
            /// </summary>
            /// <remarks>
            /// Create new user identity
            /// </remarks>
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='version'>
            /// </param>
            /// <param name='createIdentityModel'>
            /// Create user identity information
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<UserIdentity> ApiVversionIdentityPostAsync(this IVeisesUserIdentityAPI10 operations, string version, CreateUserIdentity createIdentityModel = default(CreateUserIdentity), CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.ApiVversionIdentityPostWithHttpMessagesAsync(version, createIdentityModel, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

    }
}
