// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace Veises.SocialNet.Identity.Contracts.Client.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    /// <summary>
    /// User unique identifier
    /// </summary>
    public partial class UserUid
    {
        /// <summary>
        /// Initializes a new instance of the UserUid class.
        /// </summary>
        public UserUid()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the UserUid class.
        /// </summary>
        public UserUid(long? id = default(long?))
        {
            Id = id;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public long? Id { get; set; }

    }
}
